# Generated by Django 5.0.4 on 2024-04-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_is_enabled_alter_post_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
