# Generated by Django 5.0.4 on 2024-04-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_created_date_remove_post_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
