# Generated by Django 5.0.4 on 2024-04-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.FilePathField(null=True),
        ),
    ]
