# Generated by Django 5.0.4 on 2024-04-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='movie',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
